import type { Metadata } from "next";
import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import { SyncfusionProvider } from "@/components";
import { UserProvider } from "@/providers/UserContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn("font-greycliff overflow-x-hidden antialiased")}>
        <UserProvider>
          <SyncfusionProvider>{children}</SyncfusionProvider>
        </UserProvider>
      </body>
    </html>
  );
}
